In [1]:
import numpy as np

## Arrays o Vectores

In [2]:
# 1-D
np.array([1, 4, 7])

array([1, 4, 7])

In [3]:
# 2-D
np.array([[1, 3], [2, 4]])

array([[1, 3],
       [2, 4]])

In [4]:
## Array unos
np.ones((4, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [5]:
## Array ceros
np.zeros((4, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
## Array identidad
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Matrices

In [7]:
# matriz de 3x3
np.matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [8]:
np.matrix('1 2 3; 4 5 6; 7 8 9')

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

## Numeros entre intervalos iguales

In [9]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [10]:
np.linspace(10, 0, 3)

array([10.,  5.,  0.])

In [11]:
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

## Numeros Aleatorios

In [12]:
# numero entre 0 y 1
np.random.random()

0.006502270994031667

In [13]:
# lista de n numeros aleatorios entre 0 y 1
np.random.random(3)

array([0.88599051, 0.0046014 , 0.37945474])

In [14]:
# numeros de 2 filas y 3 columnas
np.random.rand(2,3)

array([[0.79008022, 0.2773218 , 0.72878095],
       [0.40903166, 0.53119129, 0.67005747]])

In [15]:
# numeros enteros
np.random.randint(6, size=4)

array([2, 0, 0, 3])

## Forma y Dimensión Vectores

### Forma

In [16]:
np.random.rand(2,3).shape # función .shape

(2, 3)

In [17]:
np.random.rand(3).shape

(3,)

In [18]:
np.matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]]).shape

(3, 3)

### Dimensiones

In [19]:
np.random.rand(2,3).ndim # función .ndim

2

In [20]:
np.random.rand(3).ndim

1

In [21]:
np.matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]]).ndim

2

### Número de elementos

In [22]:
np.random.rand(2,3).size # función .size

6

In [23]:
np.random.rand(3).size

3

In [24]:
np.matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]]).size

9

### Transpuesta

In [25]:
lista = np.array([[1, 2, 3]])
transpuesta = lista.T

In [26]:
print('lista: \n', lista.shape)
print('lista transpuesta: \n', transpuesta.shape)

lista: 
 (1, 3)
lista transpuesta: 
 (3, 1)


In [27]:
lista = np.matrix('1 2 3; 4 5 6; 7 8 9')
transpuesta = lista.T # función .T

In [28]:
print('lista: \n', lista)
print('lista transpuesta: \n', transpuesta)

lista: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
lista transpuesta: 
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


## Acceso a los elementos

In [29]:
# acceder al elemento de la 3º columna 2º fila
lista = np.matrix('1 2 3; 4 5 6; 7 8 9')
lista[1,2]

6

In [30]:
# acceder a la 2º fila
lista[1,:]

matrix([[4, 5, 6]])

In [31]:
# acceder a la 3º columna
lista[:,2]

matrix([[3],
        [6],
        [9]])